# 【PyTorch】すべての要素が0/1の配列生成するtorch.zeros、torch.zeros_like、torch.ones、torch.ones_like
https://take-tech-engineer.com/pytorch-zeros-ones/

In [1]:
import torch

a = torch.zeros(5)
print(a)
# tensor([0., 0., 0., 0., 0.])
print(a.shape)
# torch.Size([5])
print(a.dtype)
# torch.float32

b = torch.zeros(2, 3)
print(b)
# tensor([[0., 0., 0.],
#        [0., 0., 0.]])
print(b.shape)
# torch.Size([2, 3])

c = torch.zeros(3, 3, 2)
print(c.shape)
# torch.Size([3, 3, 2])

tensor([0., 0., 0., 0., 0.])
torch.Size([5])
torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])
torch.Size([3, 3, 2])


In [2]:
d = torch.zeros(2, dtype=torch.int8)
print(d.dtype)
# torch.int8

torch.int8


In [3]:
a = torch.ones(5)
print(a)
# tensor([1., 1., 1., 1., 1.])
print(a.shape)
# torch.Size([5])
print(a.dtype)
# torch.float32

b = torch.ones(2, 3)
print(b)
# tensor([[1., 1., 1.],
#         [1., 1., 1.]])
print(b.shape)
# torch.Size([2, 3])

c = torch.ones(3, 3, 2)
print(c.shape)
# torch.Size([3, 3, 2])

tensor([1., 1., 1., 1., 1.])
torch.Size([5])
torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])
torch.Size([3, 3, 2])


In [4]:
a = torch.rand(2, 3)
print(a)
# tensor([[0.3804, 0.1059, 0.7642],
#        [0.9733, 0.8222, 0.0327]])
print(a.shape)
# torch.Size([2, 3])

b = torch.zeros_like(a)
print(b)
# tensor([[0., 0., 0.],
#        [0., 0., 0.]])
print(b.shape)
# torch.Size([2, 3])
print(b.dtype)
# torch.float32

tensor([[0.7046, 0.5073, 0.0559],
        [0.5722, 0.4954, 0.5208]])
torch.Size([2, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.Size([2, 3])
torch.float32


In [5]:
a = torch.rand(2, 3)
print(a)
# tensor([[0.3185, 0.7047, 0.8822],
#        [0.9370, 0.9441, 0.0713]])
print(a.shape)
# torch.Size([2, 3])

b = torch.ones_like(a)
print(b)
# tensor([[1., 1., 1.],
#        [1., 1., .]])
print(b.shape)
# torch.Size([2, 3])
print(b.dtype)
# torch.float32

tensor([[0.3612, 0.1392, 0.9862],
        [0.2054, 0.9148, 0.1337]])
torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])
torch.float32
