# Numpyでランダムな整数を生成するnumpy.random.randint
https://take-tech-engineer.com/numpy-random-randint/

In [1]:
import numpy as np

value = np.random.randint(low=3, high=5, size=(3,))
print(value)
print(type(value))
print(value.dtype)

[3 3 4]
<class 'numpy.ndarray'>
int64


In [2]:
print(np.random.randint(low=3, high=5, size=(3,2)))

[[4 3]
 [4 3]
 [4 4]]


In [3]:
value = np.random.randint(low=3, size=(3,))
print(value)

[0 2 1]


In [4]:
print(np.random.randint(low=[1, 5, 7], high=10))

print(np.random.randint(low=1, high=[3, 5, 10]))

[7 8 8]
[1 4 4]
