# 最大値、最小値を取得するtorch.max、torch.min
https://take-tech-engineer.com/pytorch-max-min/

In [1]:
import torch

In [2]:
a = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12],])
print(a)
print(a.shape)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
torch.Size([3, 4])


In [3]:
print(torch.max(a))

tensor(12)


In [4]:
print(torch.max(a,dim=0))

print(torch.max(a,dim=0).values)

print(torch.max(a,dim=1))

print(torch.max(a,dim=1).values)

torch.return_types.max(
values=tensor([ 9, 10, 11, 12]),
indices=tensor([2, 2, 2, 2]))
tensor([ 9, 10, 11, 12])
torch.return_types.max(
values=tensor([ 4,  8, 12]),
indices=tensor([3, 3, 3]))
tensor([ 4,  8, 12])


In [5]:
print(torch.min(a))

tensor(1)


In [6]:
print(torch.min(a,dim=0))

print(torch.min(a,dim=0).values)

print(torch.min(a,dim=1))

print(torch.min(a,dim=1).values)

torch.return_types.min(
values=tensor([1, 2, 3, 4]),
indices=tensor([0, 0, 0, 0]))
tensor([1, 2, 3, 4])
torch.return_types.min(
values=tensor([1, 5, 9]),
indices=tensor([0, 0, 0]))
tensor([1, 5, 9])
