# 2つのTensor配列の要素ごとの最大値・最小値を取得するtorch.maximum、torch.minimum、torch.fmax、torch.fmin【PyTorch】
https://take-tech-engineer.com/pytorch-max-min/

In [1]:
import torch

a = torch.tensor((1, 2, -1))
b = torch.tensor((3, 0, 4))

print(torch.maximum(a, b))

print(torch.fmax(a, b))

tensor([3, 2, 4])
tensor([3, 2, 4])


In [2]:
a = torch.tensor((1, 2, -1))
b = torch.tensor((0))

print(torch.maximum(a, b))

print(torch.fmax(a, b))

tensor([1, 2, 0])
tensor([1, 2, 0])


In [3]:
a = torch.tensor((1, float('nan'), -1))
b = torch.tensor((3, 0, 4))

print(torch.maximum(a, b))

print(torch.fmax(a, b))

tensor([3., nan, 4.])
tensor([3., 0., 4.])


In [4]:
a = torch.tensor((1, 2, -1))
b = torch.tensor((3, 0, 4))

print(torch.minimum(a, b))

print(torch.fmin(a, b))

tensor([ 1,  0, -1])
tensor([ 1,  0, -1])


In [5]:
a = torch.tensor((1, 2, -1))
b = torch.tensor((0))

print(torch.minimum(a, b))

print(torch.fmin(a, b))

tensor([ 0,  0, -1])
tensor([ 0,  0, -1])


In [6]:
a = torch.tensor((1, float('nan'), -1))
b = torch.tensor((3, 0, 4))

print(torch.minimum(a, b))

print(torch.fmin(a, b))

tensor([ 1., nan, -1.])
tensor([ 1.,  0., -1.])
