# 【PyTorch】Tensor配列の最大値・最小値のインデックスを取得するtorch.argmax、torch.argmin【位置】
https://take-tech-engineer.com/pytorch-argmax-argmin/

In [1]:
import torch

a = torch.tensor([1, 3, 2])
print(torch.argmax(a))
# tensor(1)

a = torch.tensor([[0, 3, 8],
                 [6, 1, 4],
                 [5, 7, 2]])

print(torch.argmax(a))
# tensor(2)
print(torch.flatten(a))
# tensor([0, 3, 8, 6, 1, 4, 5, 7, 2])

tensor(1)
tensor(2)
tensor([0, 3, 8, 6, 1, 4, 5, 7, 2])


In [2]:
print(torch.argmax(a, dim=0))
# tensor([1, 2, 0])
print(torch.argmax(a, dim=1))
# tensor([2, 0, 1])

tensor([1, 2, 0])
tensor([2, 0, 1])


In [3]:
print(torch.max(a,dim=0))
# torch.return_types.max(values=tensor([6, 7, 8]),indices=tensor([1, 2, 0]))

print(torch.max(a,dim=0).indices)
# tensor([1, 2, 0])

torch.return_types.max(
values=tensor([6, 7, 8]),
indices=tensor([1, 2, 0]))
tensor([1, 2, 0])


In [4]:
print(torch.argmin(a))
# tensor(0)
print(torch.flatten(a))
# tensor([0, 3, 8, 6, 1, 4, 5, 7, 2])

tensor(0)
tensor([0, 3, 8, 6, 1, 4, 5, 7, 2])


In [5]:
print(torch.argmin(a, dim=0))
# tensor([0, 1, 2])
print(torch.argmin(a, dim=1))
# tensor([0, 1, 2])

tensor([0, 1, 2])
tensor([0, 1, 2])


In [6]:
print(torch.min(a,dim=0))
# torch.return_types.min(values=tensor([0, 1, 2]),indices=tensor([0, 1, 2]))

print(torch.min(a,dim=0).indices)
# tensor([1, 2, 0])

torch.return_types.min(
values=tensor([0, 1, 2]),
indices=tensor([0, 1, 2]))
tensor([0, 1, 2])
