# PyTorch配列Tesonrを任意の最小値・最大値に収めるclamp
https://take-tech-engineer.com/python-pytorch-clamp/

In [1]:
import torch

In [10]:
a = torch.tensor([-1.0, -0.4, 0.0, 0.3, 0.9])
print(a)

tensor([-1.0000, -0.4000,  0.0000,  0.3000,  0.9000])


In [13]:
print(torch.clamp(input=a, min=-0.5, max=0.5))

tensor([-0.5000, -0.4000,  0.0000,  0.3000,  0.5000])


In [15]:
print(torch.clamp(input=a, min=-0.5))

print(torch.clamp(input=a, max=0.5))

tensor([-0.5000, -0.4000,  0.0000,  0.3000,  0.9000])
tensor([-1.0000, -0.4000,  0.0000,  0.3000,  0.5000])


In [18]:
limit = torch.tensor([-1.2, -0.5, 0.1 , 0.5, 1.0])

print(torch.clamp(input=a, min=limit))

print(torch.clamp(input=a, max=limit))

tensor([-1.0000, -0.4000,  0.1000,  0.5000,  1.0000])
tensor([-1.2000, -0.5000,  0.0000,  0.3000,  0.9000])
