# 【PyTorch】ランダムな整数を生成するtorch.randomint
https://take-tech-engineer.com/pytorch-torch-randomint/

In [1]:
import torch

value = torch.randint(low=3, high=5, size=(3,))
print(value)
print(type(value))
print(value.dtype)

tensor([3, 3, 4])
<class 'torch.Tensor'>
torch.int64


In [2]:
print(torch.randint(low=3, high=5, size=(3,3)))

tensor([[3, 3, 4],
        [3, 3, 3],
        [4, 3, 3]])


In [3]:
print(torch.randint(10, (2, 2)))

tensor([[2, 0],
        [3, 1]])


In [4]:
print(torch.randint(10, (2, 2)))

tensor([[5, 9],
        [3, 0]])
