# 【PyTorch】平均値と中央値を算出するtorch.median、torch.mean
https://take-tech-engineer.com/pytorch-mediantorch-mean/

In [1]:
import torch

a = torch.arange(12, dtype=torch.float32).reshape(3, 4)
print(a.shape)
print(a)
# torch.Size([3, 4])
# tensor([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])


print(torch.mean(input=a))
# tensor(5.5000)

torch.Size([3, 4])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor(5.5000)


In [2]:
print(torch.mean(input=a, dim=0))
# tensor([4., 5., 6., 7.])

print(torch.mean(input=a, dim=1))
# tensor([1.5000, 5.5000, 9.5000])

tensor([4., 5., 6., 7.])
tensor([1.5000, 5.5000, 9.5000])


In [3]:
b = torch.tensor([[torch.nan, 1, 2], [1, 2, 3]])

print(b.shape)
print(b)
# torch.Size([2, 3])
# tensor([[nan, 1., 2.],
#        [1., 2., 3.]])

print(torch.mean(input=b))
# tensor(nan)

torch.Size([2, 3])
tensor([[nan, 1., 2.],
        [1., 2., 3.]])
tensor(nan)


In [4]:
print(torch.nanmean(input=b))
# tensor(1.8000)

print(torch.nanmean(input=b, dim=0))
# tensor([1.0000, 1.5000, 2.5000])

print(torch.nanmean(input=b, dim=1))
# tensor([1.5000, 2.0000])

tensor(1.8000)
tensor([1.0000, 1.5000, 2.5000])
tensor([1.5000, 2.0000])


In [5]:
print(torch.median(input=a))
# tensor(5.)

tensor(5.)


In [6]:
values, indices = torch.median(input=a, dim=0)
print(values)
print(indices)
# tensor([4., 5., 6., 7.])
# tensor([1, 1, 1, 1])

values, indices = torch.median(input=a, dim=1)
print(values)
print(indices)
# tensor([1., 5., 9.])
# tensor([1, 1, 1])

tensor([4., 5., 6., 7.])
tensor([1, 1, 1, 1])
tensor([1., 5., 9.])
tensor([1, 1, 1])


In [7]:
print(torch.median(input=b))
# tensor(nan)

tensor(nan)


In [8]:
print(torch.nanmedian(input=b))
# tensor(2.)

values, indices = torch.nanmedian(input=b, dim=0)
print(values)
print(indices)
# tensor([1., 1., 2.])
# tensor([1, 0, 0])

values, indices = torch.nanmedian(input=b, dim=1)
print(values)
print(indices)
# tensor([1, 0, 0])
# tensor([1, 1])

tensor(2.)
tensor([1., 1., 2.])
tensor([1, 0, 0])
tensor([1., 2.])
tensor([1, 1])
