# 【PyTorch】Tensor配列のユニークな要素の値、位置、数を取得するtorch.unique
https://take-tech-engineer.com/pytorch-unique/

In [1]:
import torch

a = torch.tensor([1, 3, 2, 3])
print(a)
# tensor([1, 3, 2, 3])

print(torch.unique(a))
# tensor([1, 2, 3])

print(torch.unique(a, sorted=False))
# tensor([2, 3, 1])

tensor([1, 3, 2, 3])
tensor([1, 2, 3])
tensor([2, 3, 1])


In [2]:
output, inverse_indices = torch.unique(a, return_inverse=True)

print(output)
# tensor([1, 2, 3])
print(inverse_indices)
# tensor([0, 2, 1, 2])

tensor([1, 2, 3])
tensor([0, 2, 1, 2])


In [3]:
b = torch.tensor([[1, 3, 2, 3],
                  [1, 3, 2, 3],])

output_b, inverse_indices_b = torch.unique(b, return_inverse=True)

print(output_b)
# tensor([1, 2, 3])
print(inverse_indices_b)
# tensor([[0, 2, 1, 2],
#        [0, 2, 1, 2]])

tensor([1, 2, 3])
tensor([[0, 2, 1, 2],
        [0, 2, 1, 2]])


In [4]:
output, counts  = torch.unique(a, return_counts=True)

print(output)
# tensor([1, 2, 3])
print(counts)
# tensor([1, 1, 2])

tensor([1, 2, 3])
tensor([1, 1, 2])
