# PyTorchでTensor配列の符号を取得するtorch.sign
https://take-tech-engineer.com/pytorch-sign/

In [1]:
import torch

a = torch.tensor([0.7, -1.2, 0., 2.3])
print(torch.sign(a))
# tensor([ 1., -1.,  0.,  1.])
print(a.dtype)
# torch.float32

tensor([ 1., -1.,  0.,  1.])
torch.float32


In [2]:
a = torch.tensor([0, -1, 0, 2])
print(torch.sign(a))
# tensor([ 0, -1,  0,  1])
print(a.dtype)
# torch.int64

tensor([ 0, -1,  0,  1])
torch.int64


In [3]:
a = torch.tensor([0, -0, torch.inf, -torch.inf, torch.nan])
print(torch.sign(a))
# tensor([ 0.,  0.,  1., -1.,  0.])

tensor([ 0.,  0.,  1., -1.,  0.])
