# Numpyの配列を任意の値の範囲に制限するclip
https://take-tech-engineer.com/?p=218

In [1]:
import numpy as np

In [3]:
a = np.array([-1.0, -0.4, 0.0, 0.3, 0.9])
print(a)

print(np.clip(a=a,　a_min=-0.5,　a_max=0.5))

[-1.  -0.4  0.   0.3  0.9]
[-0.5 -0.4  0.   0.3  0.5]


In [7]:
print(np.clip(a=a, a_min=-0.5, a_max=None))

print(np.clip(a=a, a_min=None, a_max=0.5))

[-0.5 -0.4  0.   0.3  0.9]
[-0.5 -0.4  0.   0.3  0.5]


In [8]:
limit = np.array([-1.2, -0.5, 0.1 , 0.5, 1.0])

print(np.clip(a=a, a_min=limit, a_max=None))

print(np.clip(a=a, a_min=None, a_max=limit))

[-1.  -0.4  0.1  0.5  1. ]
[-1.2 -0.5  0.   0.3  0.9]
