# 【PyTorch】Tensorとndarrayの変換方法について【Numpy】
https://take-tech-engineer.com/pytorch-tensor-ndarray-numpy/

In [ ]:
import torch
import numpy

In [ ]:
a = numpy.array([1, 2, 3])

t = torch.from_numpy(a)
print(t)
# tensor([1, 2, 3])

t[0] = -1
print(t)
# tensor([-1,  2,  3])
print(a)
# [-1  2  3]

In [ ]:
a = numpy.array([1, 2, 3])

t = torch.from_numpy(a).clone()
print(t)
# tensor([1, 2, 3])

t[0] = -1
print(t)
# tensor([-1,  2,  3])
print(a)
# [1 2 3]

In [ ]:
t = torch.tensor([1, 2, 3])

a = t.numpy()
print(a)
# [1 2 3]

a[0] = -1
print(a)
# [-1  2  3]
print(t)
# tensor([-1,  2,  3])

In [ ]:
t = torch.tensor([1, 2, 3])

a = t.numpy().copy()
print(a)
# [1 2 3]

a[0] = -1
print(a)
# [-1  2  3]
print(t)
# tensor([-1,  2,  3])

In [ ]:
t = torch.tensor([1, 2, 3]).to('cuda')
print(t)
# tensor([1, 2, 3], device='cuda:0')

a = t.cpu().numpy().copy()
print(a)
# [1 2 3]

In [ ]:
t = torch.tensor([1, 2, 3]).to('cuda')
print(t)
# tensor([1, 2, 3], device='cuda:0')

a = t.cpu().numpy().copy()
print(a)
# [1 2 3]

In [ ]:
t = torch.tensor([0.1, 2, 3], requires_grad=True).to('cuda')
print(t)
# tensor([0.1000, 2.0000, 3.0000], device='cuda:0', grad_fn=<ToCopyBackward0>)

a = t.cpu().detach().numpy().copy()
print(a)
# [0.1 2.  3. ]