# 【PyTorch reshape】Tensor配列の形状を変換するtorch.reshape
https://take-tech-engineer.com/pytorch-reshape/

In [3]:
import torch

a = torch.arange(4.)
print(a)
# tensor([0., 1., 2., 3.])
print(a.shape)
# torch.Size([4])


a_reshape = torch.reshape(a, (2, 2))
print(a_reshape)
# tensor([[0., 1.],
#        [2., 3.]])
print(a_reshape.shape)
# torch.Size([2, 2])


a_reshape = torch.reshape(a, (1, 4))
print(a_reshape)
# tensor([[0., 1., 2., 3.]])
print(a_reshape.shape)
# torch.Size([1, 4])

a_reshape = torch.reshape(a, (1, 5))
# RuntimeError: shape '[1, 5]' is invalid for input of size 4

tensor([0., 1., 2., 3.])
torch.Size([4])
tensor([[0., 1.],
        [2., 3.]])
torch.Size([2, 2])
tensor([[0., 1., 2., 3.]])
torch.Size([1, 4])


RuntimeError: shape '[1, 5]' is invalid for input of size 4

In [4]:
a_reshape = torch.reshape(a, (-1, 2))
print(a_reshape)
# tensor([[0., 1.],
#        [2., 3.]])
print(a_reshape.shape)
# torch.Size([2, 2])

a_reshape = torch.reshape(a, (1, -1))
print(a_reshape)
# tensor([[0., 1., 2., 3.]])
print(a_reshape.shape)
# torch.Size([1, 4])

tensor([[0., 1.],
        [2., 3.]])
torch.Size([2, 2])
tensor([[0., 1., 2., 3.]])
torch.Size([1, 4])
