# 【PyTorch】ランダムな整数の順列を生成するtorch.randperm
https://take-tech-engineer.com/pytorch-randperm/

In [1]:
import torch

print(torch.randperm(4))
# tensor([1, 3, 2, 0])
print(torch.randperm(5))
# tensor([1, 0, 3, 2, 4])

tensor([0, 3, 1, 2])
tensor([0, 3, 2, 1, 4])
